version: '3.1'
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: birdie-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/nginx.conf"
    networks:
      - birdie
  
networks:
  birdie:
    driver: bridge
