version: '3.1'
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - "./nginx/:/etc/nginx/conf.d/"
    networks:
      - web
  
networks:
  web:
    driver: bridge
